name: Main Pipeline

on:
  push:
    branches:
      # - dev
      - approval

jobs:
  dev-use1:
    uses: ./.github/workflows/tfapply.yml
    with:
      environment: development
      aws-env-dir: dev-use1
      aws-region: us-east-1

  dev-usw2:
    # base_ref is the target branch
    if: github.event_name == 'pull_request' && github.event.base_ref == 'main'
    uses: ./.github/workflows/tfapply.yml
    with:
      environment: production # Change this to 'review' or 'production' as needed
      aws-env-dir: dev-usw2
      aws-region: us-west-2
