name: Main Pipeline

on:
  push:
    branches:
      - dev

env:
  AWS_ENV: development # set as env var (Settings > Environments > Environment variables > Add variable)
  AWS_ENV_DIR: dev-use1 # set as env var the dir where the tf code of the env, to be deployed into, resides
  AWS_REGION: us-east-1 # set as env var (Settings > Environments > Environment variables > Add variable)
  IAM_ROLE_ARN: arn:aws:iam::${{ ACCOUNT_ID }}:role/github-actions-role # set as env var (Settings > Environments > Environment variables > Add variable)


jobs:
  dev-use1:
    uses: ./.github/workflows/reusable-wf.yml
    with:
      environment: development
      aws-env-dir: dev-use1
      aws-region: us-east-1

  dev-usw2:
    uses: ./.github/workflows/reusable-wf.yml
    with:
      environment: development
      aws-env-dir: dev-use1
      aws-region: us-east-1
      iam-role-arn: arn:aws:iam::${{ ACCOUNT_ID }}:role/github-actions-role
