name: Deploy Infra to AWS Env

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  dev-use1:
    uses: ./.github/workflows/tf-common.yml
    with:
      aws-env: dev-use1
      AWS_REGION: us-east-1
      IAM_ROLE_ARN: arn:aws:iam::155185327318:role/github-actions-role
