name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      environment:
        description: 'deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      path:
        required: true
        default: 'backlog'
        type: choice
        options:
          - 'backlog'
          - 'realtime'
      aws-env-dir:
        required: true
        default: 'dev-use1'
        type: choice
        options:
          - 'dev-use1'
          - 'dev-usw2'
      aws-region:
        required: true
        default: 'us-east-1'
        type: choice
        options:
          - 'us-east-1'
          - 'us-west-2'

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform-plan:
    name: Terraform Destroy Plan
    runs-on: ${{ vars.GH_RUNNER_TAG }} # use github UI to define as a repo variable
    environment: ${{ inputs.environment }}
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN_DEV }} # use github UI to define as an env variable for corresponding environment
          aws-region: ${{ inputs.aws-region }}
          role-session-name: enverus-role-session
          role-duration-seconds: 3600
          audience: sts.amazonaws.com

      - name: Check Current IAM Role
        run: aws sts get-caller-identity

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
     
      - name: Terraform Version
        run: terraform -version
        
      - name: Terraform Init
        run: |
          cd ${{ inputs.path }}/${{ inputs.aws-env-dir }}/
          rm -rf .terraform*
          terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: |
          cd ${{ inputs.path }}/${{ inputs.aws-env-dir }}/
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ inputs.path }}/${{ inputs.aws-env-dir }}/
          terraform plan -destroy -var 'python_version=${{ vars.GH_RUNNER_PY_VER }}' -out=tfplan
      
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ${{ inputs.path }}/${{ inputs.aws-env-dir }}/tfplan
  
  terraform-destroy:
    name: Terraform Destroy
    needs: terraform-plan
    runs-on: ${{ vars.GH_RUNNER_TAG }} # use github UI to define as a repo variable
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN_DEV }} # use github UI to define as an env variable for corresponding environment
          aws-region: ${{ inputs.aws-region }}
          role-session-name: enverus-role-session
          role-duration-seconds: 3600
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2

      - name: Terraform Init
        run: |
          cd ${{ inputs.path }}/${{ inputs.aws-env-dir }}/
          rm -rf .terraform*
          terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan

      - name: Terraform Destroy
        run: |
          cd ${{ inputs.path }}/${{ inputs.aws-env-dir }}/
          terraform state list
          terraform apply -destroy ../../tfplan
          terraform state list
