name: Deploy Infra to AWS Env

on:
  push:
    branches:
      - oidc
  pull_request:
    branches:
      - oidc

jobs:
  dev-use1:
    uses: ./.github/workflows/tf-common.yml
    with:
      aws-env: dev-use1
