name: Deploy Infra to AWS Env

on:
  push:
    branches:
      - env2
  pull_request:
    branches:
      - dev

env:
  AWS_ENV: development # env variable
  AWS_ENV_DIR: dev-use1 # env variable: the dir where the tf code of the env, to be deployed into, resides
  AWS_REGION: us-east-1 # env variable
  IAM_ROLE_ARN: arn:aws:iam::155185327318:role/github-actions-role # env variable

jobs:
  vars:
    runs-on: ubuntu-22.04
    outputs:
      aws-env-out: ${{ env.AWS_ENV }}
      aws-env-dir-out: ${{ env.AWS_ENV_DIR }}
      aws-region-out: ${{ env.AWS_REGION }}
      iam-role-arn-out: ${{ env.IAM_ROLE_ARN }}
    steps:
      - run: echo "Exposing env vars"

  dev-use1:
    needs: vars
    uses: ./.github/workflows/tf-common.yml
    with:
      aws-env: ${{ needs.vars.outputs.aws-env-out }}
      # aws-env: development
      aws-env-dir: ${{ needs.vars.outputs.aws-env-dir-out }}
      # aws-env-dir: dev-use1
      aws-region: ${{ needs.vars.outputs.aws-region-out }}
      # aws-region: us-east-1
      iam-role-arn: ${{ needs.vars.outputs.iam-role-arn-out }}
      # iam-role-arn: arn:aws:iam::155185327318:role/github-actions-role
