name: Terraform Destroy

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
    inputs:
      env:
        description: 'deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
      data-pipeline:
        required: true
        default: 'batch'
        type: choice
        options:
          - 'batch'
          - 'realtime'
      aws-region:
        required: true
        default: 'us-east-1'
        type: choice
        options:
          - 'us-east-1'
          - 'us-west-2'
      lambda-role-name:
        required: true
        default: 'llandman-dev-lambda-exec-role'
        type: string

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform-plan:
    name: Terraform Destroy Plan
    runs-on: ${{ vars.GH_RUNNER_TAG }} # use github UI to define as a repo variable
    environment: ${{ inputs.env }}
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN_DEV }} # use github UI to define as an env variable for corresponding environment
          aws-region: ${{ inputs.aws-region }}
          role-session-name: enverus-role-session
          role-duration-seconds: 3600
          audience: sts.amazonaws.com

      - name: Install Dependencies
      run: |
        pip install jinja2==3.1.4 && pip show jinja2
        pip install PyYAML==6.0.2 && pip show PyYAML
  
      - name: Terraform Files Generation
        run: |
          cp scripts/generate-tfiles.py ${{ inputs.data-pipeline }}/
          cd ${{ inputs.data-pipeline }}/
          export BUCKET=${{ inputs.tfbackend_bucket }}
          export KEY=${{ inputs.tfbackend_key }}
          export BACKEND_REGION=${{ inputs.tfbackend_region }}
          export PROVIDER_REGION=${{ inputs.tfprovider_region }}
          export ALIAS=${{ inputs.tfprovider_alias }}
          export ENV=${{ inputs.env }}
          chmod +x generate-tfiles.py
          python generate-tfiles.py
          echo && cat backend.tf
          echo && cat providers.tf

      - name: Check Current IAM Role
        run: aws sts get-caller-identity

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2
          # cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
     
      - name: Terraform Version
        run: terraform -version
        
      - name: Terraform Init
        run: |
          cd ${{ inputs.data-pipeline }}/
          rm -rf .terraform*
          terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: |
          cd ${{ inputs.data-pipeline }}/
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ inputs.data-pipeline }}/
          lambda_layer_version_arn=$(aws lambda list-layer-versions \
                                          --layer-name python-libs \
                                          --query 'LayerVersions[0].LayerVersionArn' \
                                          --output text)
          terraform plan -destroy \
            -var env=${{ inputs.env }} \
            -var lambda_role_name=${{ inputs.lambda-role-name }} \
            -var python_version=${{ vars.GH_RUNNER_PY_VER }} \
            -var lambda_layer_version_arn=$lambda_layer_version_arn \
            -out=tfplan
          # terraform plan -destroy -var 'python_version=${{ vars.GH_RUNNER_PY_VER }}' -out=tfplan
      
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ${{ inputs.data-pipeline }}/tfplan
  
  terraform-destroy:
    name: Terraform Destroy
    needs: terraform-plan
    runs-on: ${{ vars.GH_RUNNER_TAG }} # use github UI to define as a repo variable
    environment: ${{ inputs.env }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.IAM_ROLE_ARN_DEV }} # use github UI to define as an env variable for corresponding environment
          aws-region: ${{ inputs.aws-region }}
          role-session-name: enverus-role-session
          role-duration-seconds: 3600
          audience: sts.amazonaws.com

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2

      - name: Terraform Init
        run: |
          cd ${{ inputs.data-pipeline }}/
          rm -rf .terraform*
          terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan

      - name: Terraform Destroy
        run: |
          cd ${{ inputs.data-pipeline }}/
          terraform state list
          terraform apply -destroy ../../tfplan
          terraform state list
