name: Deploy Infra to AWS Env

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  dev-use1:
    uses: ./.github/workflows/tf-common.yml
    with:
      aws-env: development
      aws-env-dir: dev-use1
      aws-region: us-east-1
      # iam-role-arn: arn:aws:iam::${{ ACCOUNT_ID }}:role/github-actions-role
      iam-role-arn: arn:aws:iam::155185327318:role/github-actions-role
