name: Deploy Infra to AWS Env

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

env:
  AWS-ENV: dev-use1 # the dir where the tf code of the env, to be deployed into, resides
  AWS_REGION: us-east-1
  IAM_ROLE_ARN: arn:aws:iam::155185327318:role/github-actions-role

jobs:
  dev-use1:
    uses: ./.github/workflows/tf-common.yml
    with:
      aws-env: ${{ env.AWS-ENV }}
      AWS_REGION: ${{ env.AWS_REGION }}
      IAM_ROLE_ARN: ${{ env.IAM_ROLE_ARN }}
