name: 'Terraform Unit Tests'

on:
    workflow_call:
      inputs:
        environment:
          required: true
          type: string
        aws-env-dir:
          required: true
          type: string
        aws-region:
          required: true
          type: string

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform-unit-tests:
    name: 'Terraform Unit Tests'
    runs-on: ${{ vars.GH_RUNNER_TAG }} # define as an env var from UI for corresponding environment
    environment: ${{ inputs.environment }}

    defaults:
      run:
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Creds
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ vars.IAM_ROLE_ARN_DEV }} # ensure this var is added under `development` env in github
        aws-region: ${{ inputs.aws-region }}
        role-session-name: gh-actions-session
        role-duration-seconds: 3600
        audience: sts.amazonaws.com

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.2

    - name: Terraform Version
      run: terraform -version
        
    - name: Terraform Init
      run: |
        cd ${{ inputs.aws-env-dir }}/
        rm -rf .terraform*
        terraform init

    - name: Terraform Validate
      run: |
        cd ${{ inputs.aws-env-dir }}/
        terraform validate

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check -recursive
    
    # Perform a security scan of the terraform code using checkov
    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with: 
        framework: terraform
        # CKV_AWS_272(lambda code-signing), CKV_AWS_18(s3 bucket access logging), CKV_AWS_144(s3 cross-region replication) 
        skip_check: CKV_AWS_272,CKV_AWS_18,CKV_AWS_144,CKV_AWS_290,CKV_AWS_355,CKV_TF_1
